### ISSUE TITLE
SolrCloud / Solr v.8 Schema Error: Plugin init failure for solr.StandardFilterFactory

### ISSUE THREAD

**Issue by cmharlow** [tulibraries/tul_cob#1285]
```Caused by: org.apache.solr.common.SolrException: Could not load conf for core blacklight_shard1_replica_n2: Can't load schema schema.xml: Plugin init failure for [schema.xml] fieldType "textSpell": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'solr.StandardFilterFactory'
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:96)
	at org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1287)
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1234)```

**Comment by cmharlow** [comment]
Removed.
