### ISSUE TITLE
Traject shoud commit more often

### ISSUE THREAD

**Issue by bibliotechy** [tulibraries/tul_cob#2]
When I tried to ingest a large number of records, solr ran out of memory. I suspect it is because it waited to commit all records at the end.

Investigate if traject lets you commit more often via config.

**Comment by skng5** [comment]
If this is the problem:

```
2016-12-01T22:02:20+00:00  INFO Traject::SolrJsonWriter sending commit to solr at url http://127.0.0.1:8983/solr/blacklight-core/update/json...
rake aborted!
HTTPClient::ReceiveTimeoutError: execution expired

Tasks: TOP => solr:marc:index => solr:marc:index:work
(See full trace by running task with --trace)
```

then it may be timing out waiting for the final commit to complete and we should find a way to extend the timeout.

**Comment by bibliotechy** [comment]
@skng5  This is how it was failing for me
```
2016-12-01T16:04:37-05:00  WARN Traject::SolrJsonWriter: 546 skipped records
2016-12-01T16:04:37-05:00  INFO Traject::SolrJsonWriter sending commit to solr at url http://127.0.0.1:8983/solr/blacklight-core/update/json...
rake aborted!
HTTPClient::ReceiveTimeoutError: execution expired
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:799:in `gets'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:799:in `block in parse_header'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:795:in `parse_header'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:778:in `read_header'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:554:in `get_header'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1297:in `do_get_header'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1243:in `do_get_block'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1017:in `block in do_request'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:1012:in `do_request'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:854:in `request'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.2.4/lib/httpclient.rb:741:in `get'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/traject-2.3.2/lib/traject/solr_json_writer.rb:210:in `commit'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/traject-2.3.2/lib/traject/solr_json_writer.rb:197:in `close'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/traject-2.3.2/lib/traject/indexer.rb:493:in `process'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/bundler/gems/blacklight-marc-0e9d4a39f12e/lib/railties/solr_marc.rake:53:in `block (5 levels) in <top (required)>'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/bundler/gems/blacklight-marc-0e9d4a39f12e/lib/railties/solr_marc.rake:52:in `block (4 levels) in <top (required)>'
/var/www/tul_cob/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/tul_cob/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/tul_cob/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => solr:marc:index => solr:marc:index:work
(See full trace by running task with --trace)

```

**Comment by bibliotechy** [comment]
This has been handled in `solr_config.xml` instead.
